### ISSUE TITLE
"yarn start" & "yarn dev" fail on Windows 10

### ISSUE THREAD

**Issue by ukozdan** [danilowoz/react-atomic-design#2]
`$ yarn start`
`yarn run v1.6.0`
`$ node dist-server/server.js`
`module.js:557`
`    throw err;
    ^`

`Error: Cannot find module 'C:\Users\sandeda\Documents\GitHub\react-atomic-design\dist-server\server.js'`
    `at Function.Module._resolveFilename (module.js:555:15)`
    `at Function.Module._load (module.js:482:25)`
    `at Function.Module.runMain (module.js:701:10)`
    `at startup (bootstrap_node.js:193:16)`
    `at bootstrap_node.js:617:3`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

`$ yarn dev`
`yarn run v1.6.0`
`$ NODE_ENV=development PORT=5000 node server.dev.js`
`'NODE_ENV' is not recognized as an internal or external command,`
`operable program or batch file.`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by FoxGit** [comment]
`$ yarn start
yarn run v1.7.0
$ node dist-server/server.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/hansenj/Downloads/react-atomic-design/dist-server/server.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Same on Ubuntu ;)

**Comment by rupesx26** [comment]
Hey,
have same issue while using https://github.com/danilowoz/react-atomic-design so for that have create dist-server/server.js manually in root 

copy code from server.dev.js to dist-server/server.js
make sure about path 
const config = require('../webpack.config.dev')
const baseHTML = require('../src/index.html')

and hit "yarn start" 

its work for me!

**Comment by shwetank007** [comment]
@danilowoz 
Tried with NPM as well as yarn it's still giving the same issue.
Could you please tell the solution for the particular problem.
Thanks!

**Comment by danilowoz** [comment]
I just merged a new PR, what about now? Is it working?
Here I had no problem

Thanks

**Comment by shwetank007** [comment]
Thanks @danilowoz 
It's working.
